version: '3.8'
services:
  story-manager:
    build: .
    ports:
      - "5173:5173"  # UI
      - "8000:8000"  # API
    volumes:
      - ./config/library:/app/library
      - ./config/pgdata:/tmp/pgdata
    restart: unless-stopped
