"""CRUD operations package — re-exports all functions for backward compatibility."""

from . import audiobook as audiobook  # noqa: F401

from .books import (  # noqa: F401
    count_books as count_books,
    create_book as create_book,
    delete_all_books as delete_all_books,
    delete_book as delete_book,
    detach_book_source as detach_book_source,
    get_book as get_book,
    get_book_by_source_url as get_book_by_source_url,
    get_book_by_title as get_book_by_title,
    get_book_by_title_and_author as get_book_by_title_and_author,
    get_book_catalog as get_book_catalog,
    get_books as get_books,
    get_books_by_author as get_books_by_author,
    get_books_by_ids as get_books_by_ids,
    get_books_without_series as get_books_without_series,
    get_all_books_including_deleted as get_all_books_including_deleted,
    get_recycled_books as get_recycled_books,
    get_pending_refresh_books as get_pending_refresh_books,
    get_pending_web_books as get_pending_web_books,
    get_web_books as get_web_books,
    reset_failed_web_book_for_retry as reset_failed_web_book_for_retry,
    recycle_all_books as recycle_all_books,
    recycle_book as recycle_book,
    restore_recycled_book as restore_recycled_book,
    search_books as search_books,
    touch_book_content as touch_book_content,
    update_book as update_book,
)
from .series import (  # noqa: F401
    cleanup_orphaned_series_metadata as cleanup_orphaned_series_metadata,
    compute_effective_series_genre_tags as compute_effective_series_genre_tags,
    get_all_series as get_all_series,
    get_books_by_series as get_books_by_series,
    get_series_metadata as get_series_metadata,
    get_series_metadata_for_names as get_series_metadata_for_names,
    merge_series as merge_series,
    rename_series as rename_series,
    reorder_series_books as reorder_series_books,
    set_series_user_genre_tags as set_series_user_genre_tags,
    validate_genre_tags as validate_genre_tags,
)
from .logs import (  # noqa: F401
    complete_update_task as complete_update_task,
    count_book_logs as count_book_logs,
    create_book_log as create_book_log,
    create_update_task as create_update_task,
    fail_update_task as fail_update_task,
    get_book_logs as get_book_logs,
    get_active_update_task as get_active_update_task,
    get_book_logs_for_task as get_book_logs_for_task,
    get_latest_book_log as get_latest_book_log,
    get_latest_update_task as get_latest_update_task,
    get_update_tasks as get_update_tasks,
    increment_update_task as increment_update_task,
    interrupt_update_task as interrupt_update_task,
    reset_stuck_update_tasks as reset_stuck_update_tasks,
)
from .cleaning import (  # noqa: F401
    create_cleaning_config as create_cleaning_config,
    delete_cleaning_config as delete_cleaning_config,
    get_all_matching_cleaning_configs as get_all_matching_cleaning_configs,
    get_cleaning_config as get_cleaning_config,
    get_cleaning_configs as get_cleaning_configs,
    get_matching_cleaning_config as get_matching_cleaning_config,
    update_cleaning_config as update_cleaning_config,
)
from .reader import (  # noqa: F401
    get_all_reader_books as get_all_reader_books,
    get_reader_book as get_reader_book,
    get_reader_books as get_reader_books,
    get_reader_books_by_series as get_reader_books_by_series,
    get_reader_books_by_series_names as get_reader_books_by_series_names,
    get_reader_series as get_reader_series,
    get_reader_standalone_books as get_reader_standalone_books,
    get_reader_updates as get_reader_updates,
    search_reader_books as search_reader_books,
)
from .scheduler_settings import (  # noqa: F401
    get_scheduler_settings as get_scheduler_settings,
    upsert_scheduler_settings as upsert_scheduler_settings,
)
from .api_keys import (  # noqa: F401
    create_api_key as create_api_key,
    get_api_keys as get_api_keys,
    revoke_api_key as revoke_api_key,
)
from .processing import (  # noqa: F401
    claim_processing_job as claim_processing_job,
    complete_processing_job as complete_processing_job,
    create_processing_job as create_processing_job,
    defer_processing_job_for_backup as defer_processing_job_for_backup,
    fail_processing_job as fail_processing_job,
    get_processing_job as get_processing_job,
    get_processing_jobs as get_processing_jobs,
    heartbeat_processing_job as heartbeat_processing_job,
    is_processing_job_cancel_requested as is_processing_job_cancel_requested,
    mark_processing_job_canceled as mark_processing_job_canceled,
    recover_abandoned_processing_jobs as recover_abandoned_processing_jobs,
    request_processing_job_cancel as request_processing_job_cancel,
    retry_processing_job as retry_processing_job,
    update_processing_job_progress as update_processing_job_progress,
)
from .metadata import (  # noqa: F401
    complete_metadata_sync_job as complete_metadata_sync_job,
    create_metadata_sync_job as create_metadata_sync_job,
    fail_metadata_sync_job as fail_metadata_sync_job,
    get_latest_metadata_sync_job as get_latest_metadata_sync_job,
    get_metadata_inbox_entries as get_metadata_inbox_entries,
    get_metadata_match as get_metadata_match,
    get_metadata_match_by_book_id as get_metadata_match_by_book_id,
    get_metadata_matches_by_book_id as get_metadata_matches_by_book_id,
    get_metadata_proposal as get_metadata_proposal,
    get_metadata_proposal_by_book_id as get_metadata_proposal_by_book_id,
    get_metadata_sync_job as get_metadata_sync_job,
    get_pending_metadata_sync_jobs as get_pending_metadata_sync_jobs,
    get_stale_books_for_metadata_sync as get_stale_books_for_metadata_sync,
    mark_metadata_sync_job_progress as mark_metadata_sync_job_progress,
    mark_metadata_sync_job_running as mark_metadata_sync_job_running,
    reset_running_metadata_sync_jobs as reset_running_metadata_sync_jobs,
)

from .catalog import (  # noqa: F401
    build_catalog_filter_conditions as build_catalog_filter_conditions,
    get_catalog_book_page as get_catalog_book_page,
    get_catalog_facets as get_catalog_facets,
    get_catalog_series_page as get_catalog_series_page,
    get_catalog_snapshot_max_id as get_catalog_snapshot_max_id,
    get_catalog_total_count as get_catalog_total_count,
)
