"""CRUD operations package — re-exports all functions for backward compatibility."""

from .books import (  # noqa: F401
    count_books,
    create_book,
    delete_all_books,
    delete_book,
    detach_book_source,
    get_book,
    get_book_by_source_url,
    get_book_by_title,
    get_book_by_title_and_author,
    get_book_catalog,
    get_books,
    get_books_by_author,
    get_books_by_ids,
    get_books_without_series,
    get_pending_web_books,
    get_web_books,
    search_books,
    touch_book_content,
    update_book,
)
from .series import (  # noqa: F401
    cleanup_orphaned_series_metadata,
    compute_effective_series_genre_tags,
    get_all_series,
    get_books_by_series,
    get_series_metadata,
    get_series_metadata_for_names,
    merge_series,
    rename_series,
    reorder_series_books,
    set_series_user_genre_tags,
    validate_genre_tags,
)
from .logs import (  # noqa: F401
    complete_update_task,
    count_book_logs,
    create_book_log,
    create_update_task,
    fail_update_task,
    get_active_update_task,
    get_book_logs_for_task,
    get_latest_book_log,
    get_latest_update_task,
    get_update_tasks,
    increment_update_task,
    interrupt_update_task,
    reset_stuck_update_tasks,
)
from .cleaning import (  # noqa: F401
    create_cleaning_config,
    delete_cleaning_config,
    get_all_matching_cleaning_configs,
    get_cleaning_config,
    get_cleaning_configs,
    get_matching_cleaning_config,
    update_cleaning_config,
)
from .reader import (  # noqa: F401
    get_all_reader_books,
    get_reader_book,
    get_reader_books,
    get_reader_books_by_series,
    get_reader_books_by_series_names,
    get_reader_series,
    get_reader_standalone_books,
    get_reader_updates,
    search_reader_books,
)
from .scheduler_settings import (  # noqa: F401
    get_scheduler_settings,
    upsert_scheduler_settings,
)
from .api_keys import (  # noqa: F401
    create_api_key,
    get_api_keys,
    revoke_api_key,
)
from .metadata import (  # noqa: F401
    complete_metadata_sync_job,
    create_metadata_sync_job,
    fail_metadata_sync_job,
    get_latest_metadata_sync_job,
    get_metadata_inbox_entries,
    get_metadata_match,
    get_metadata_match_by_book_id,
    get_metadata_proposal,
    get_metadata_proposal_by_book_id,
    get_metadata_sync_job,
    get_pending_metadata_sync_jobs,
    get_stale_books_for_metadata_sync,
    mark_metadata_sync_job_progress,
    mark_metadata_sync_job_running,
    reset_running_metadata_sync_jobs,
)
