"""Add immutable epub path and processing fields

Revision ID: 0002
Revises: 0001_initial
Create Date: 2025-11-01 05:14:52.292572

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0002"
down_revision = "0001_initial"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("immutable_path", sa.String(), nullable=True))
    op.add_column("books", sa.Column("current_path", sa.String(), nullable=True))
    op.add_column("books", sa.Column("removed_chapters", sa.JSON(), nullable=True))
    op.add_column("books", sa.Column("div_selectors", sa.JSON(), nullable=True))
    op.add_column("books", sa.Column("master_word_count", sa.Integer(), nullable=True))
    op.add_column("books", sa.Column("current_word_count", sa.Integer(), nullable=True))
    op.drop_constraint("books_epub_path_key", "books", type_="unique")
    op.create_unique_constraint(None, "books", ["current_path"])
    op.create_unique_constraint(None, "books", ["immutable_path"])
    op.drop_column("books", "epub_path")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("epub_path", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, "books", type_="unique")
    op.drop_constraint(None, "books", type_="unique")
    op.create_unique_constraint("books_epub_path_key", "books", ["epub_path"], postgresql_nulls_not_distinct=False)
    op.drop_column("books", "current_word_count")
    op.drop_column("books", "master_word_count")
    op.drop_column("books", "div_selectors")
    op.drop_column("books", "removed_chapters")
    op.drop_column("books", "current_path")
    op.drop_column("books", "immutable_path")
    # ### end Alembic commands ###
