ALTER TABLE audiobook_settings
    ADD COLUMN transcription_provider VARCHAR,
    ADD COLUMN transcription_api_key VARCHAR,
    ADD COLUMN transcription_base_url VARCHAR,
    ADD COLUMN transcription_model VARCHAR,
    ADD COLUMN transcription_language VARCHAR;

INSERT INTO audiobook_settings (
    transcription_provider,
    transcription_base_url,
    transcription_model,
    transcription_language
) VALUES (
    'whisperx',
    'http://preexisting-whisper:8002',
    'small',
    'en'
);

CREATE TABLE imported_audiobooks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    name VARCHAR NOT NULL,
    source_type VARCHAR NOT NULL DEFAULT 'upload',
    asin VARCHAR,
    status VARCHAR NOT NULL DEFAULT 'queued',
    alignment_method VARCHAR,
    original_filenames JSON,
    duration_ms BIGINT,
    progress_current INTEGER NOT NULL DEFAULT 0,
    progress_total INTEGER NOT NULL DEFAULT 0,
    progress_detail VARCHAR,
    error TEXT,
    alignment_error TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE imported_audiobook_tracks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imported_audiobook_id INTEGER NOT NULL REFERENCES imported_audiobooks(id) ON DELETE CASCADE,
    matched_chapter_id INTEGER REFERENCES audiobook_chapters(id) ON DELETE SET NULL,
    sequence_order INTEGER NOT NULL,
    title VARCHAR NOT NULL,
    audio_file_path VARCHAR NOT NULL,
    media_type VARCHAR NOT NULL,
    source_start_ms BIGINT NOT NULL DEFAULT 0,
    source_end_ms BIGINT NOT NULL,
    duration_ms BIGINT NOT NULL,
    transcript_file_path VARCHAR,
    alignment_score DOUBLE PRECISION,
    CONSTRAINT uq_imported_audiobook_track_order
        UNIQUE (imported_audiobook_id, sequence_order)
);

CREATE TABLE imported_audiobook_cues (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_id INTEGER NOT NULL REFERENCES imported_audiobook_tracks(id) ON DELETE CASCADE,
    sentence_id INTEGER NOT NULL REFERENCES audiobook_sentences(id) ON DELETE CASCADE,
    sequence_order INTEGER NOT NULL,
    clip_begin_ms BIGINT NOT NULL,
    clip_end_ms BIGINT NOT NULL,
    confidence DOUBLE PRECISION,
    method VARCHAR NOT NULL DEFAULT 'estimated',
    CONSTRAINT uq_imported_audiobook_cue_sentence UNIQUE (track_id, sentence_id)
);

INSERT INTO imported_audiobooks (
    book_id,
    name,
    status,
    original_filenames,
    duration_ms
)
SELECT
    id,
    'Pre-existing imported edition',
    'ready',
    '["existing.m4b"]'::json,
    1250
FROM books
WHERE title = 'Migration Test';

INSERT INTO imported_audiobook_tracks (
    imported_audiobook_id,
    matched_chapter_id,
    sequence_order,
    title,
    audio_file_path,
    media_type,
    source_end_ms,
    duration_ms,
    transcript_file_path,
    alignment_score
)
SELECT
    imported_audiobooks.id,
    audiobook_chapters.id,
    1,
    'Existing chapter',
    'library/audiobooks/existing.m4b',
    'audio/mp4',
    1250,
    1250,
    'library/audiobooks/existing.json.gz',
    0.9
FROM imported_audiobooks
CROSS JOIN audiobook_chapters
WHERE imported_audiobooks.name = 'Pre-existing imported edition'
  AND audiobook_chapters.content_file_name = 'Text/existing.xhtml';

INSERT INTO imported_audiobook_cues (
    track_id,
    sentence_id,
    sequence_order,
    clip_begin_ms,
    clip_end_ms,
    confidence,
    method
)
SELECT
    imported_audiobook_tracks.id,
    audiobook_sentences.id,
    0,
    0,
    1250,
    0.9,
    'transcribed'
FROM imported_audiobook_tracks
CROSS JOIN audiobook_sentences
WHERE imported_audiobook_tracks.title = 'Existing chapter'
  AND audiobook_sentences.html_element_id = 'existing-sentence';
