name: preview-image

on:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Set image tag
        id: meta
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "tag=pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and cache base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.base
          tags: story-manager-base:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build image
        run: docker build --build-arg BASE_IMAGE=story-manager-base:latest -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tag }} .

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tag }}

      - name: Comment image
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        env:
          TAG: ${{ steps.meta.outputs.tag }}
        with:
          script: |
            const tag = process.env.TAG;
            const image = `${process.env.REGISTRY}/${process.env.IMAGE_NAME}:${tag}`;
            const url = `https://${process.env.REGISTRY}/${process.env.IMAGE_NAME}:${tag}`;
            const body = `Preview image available: \`${image}\`\n\n[View image in registry](${url})`;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });
