name: Publish base image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile.base'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}-base
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Dockerfile hash
        id: hash
        run: echo "sha=$(sha256sum Dockerfile.base | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      - name: Check for existing image
        id: check
        uses: tyriis/docker-image-tag-exists@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          repository: ${{ env.IMAGE_NAME }}
          tag: ${{ steps.hash.outputs.sha }}

      - name: Build and push
        if: steps.check.outputs.tag == 'not found'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.base
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.hash.outputs.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
